### ISSUE TITLE
Allow specifying an awscli profile

### ISSUE THREAD

**Issue by siebrand** [generalui/s3p#10]
Right now s3p always requires using the [default] AWS commandline client credentials. This feature request is about getting an additional parameter in which the profile name can be specified.

**Comment by siebrand** [comment]
Looks like I was overthinking this, and overlooked that I had a syntax issue in the s3p command... Self closing. Sorry.

**Comment by elliott-alt** [comment]
What was the solution?  I tried specifying a profile like this and it doesn't work
```
npx s3p ls --bucket mybucket --profile home
```

**Comment by siebrand** [comment]
Instance profile in EC2 or default profile.

**Comment by elliott-alt** [comment]
Oh I see.  Yes that works, as does the AWS_ACCESS_KEY_ID env variable, but I still think it would be nice to specify a different profile on the command line.

**Comment by siebrand** [comment]
Sure. Add it as a feature request. My top feature would be #21
