### ISSUE TITLE
Tested this but couldnt get the same result

### ISSUE THREAD

**Issue by mangaldev** [generalui/s3p#12]
Try to copy a 200gig folder from s3 to aws ec2 24xlarge box. 

This was the result 284mbps

s3p: d: 11m 58s, items: 14537, items/s: 20, listRequests: 30, copied 14537/14537 199.64gB/199.64gB 284.69mB/s inFlight: 0_B copyWorkers: 0 + 0, DONE
copiedBytes: 214365165520, copiedBytesPerSecond: 298515071.6320124, copiedFiles: 14537, duration: 718.1050000190735, items: 14537, itemsPerSecond: 20, requests: 30, human:
copiedBytes: :199.64gB
copiedBytesPerSecond: :284.69mB

How can we increase the thread/workercount etc?

**Comment by consigliere23** [comment]
Same here, seems that s3p does nothing...

**Comment by shanebdavis** [comment]
You can try tweaking any number of these options:

```
  --copy-concurrency 500 (ADVANCED)
  --large-copy-concurrency 75 (ADVANCED)
  --large-copy-threshold 104857600 (ADVANCED)
  --list-concurrency 100 (ADVANCED)
  --max-queue-size 50000 (ADVANCED)
```

Many factors can impact copying performance. The main ones are the average file size and the distribution of keys copied. You'll get maximum performance If the average file sizes are large (>100mb) and the item keys are evenly distributed (e.g. random id-strings).

That said, tweaking some of the params above (both up AND down) might improve your performance. Also, if your bucket is heterogeneous, as in different parts have very different sizes of files and key-distributions, running S3P separately over different sub-ranges could also help with your overall performance.
