### ISSUE TITLE
Compatibility with RequestPayer bucket?

### ISSUE THREAD

**Issue by pratheekrebala** [generalui/s3p#13]
Is it possible to use this tool with RequestPayer buckets? I think the aws-sdk supports this - just need to pass `RequestPayer: Requester` to the call to api methods.

**Comment by siebrand** [comment]
This option doesn't appear to have been implemented yet.

**Comment by shanebdavis** [comment]
Good idea.

**Comment by pratheekrebala** [comment]
Hey @shanebdavis, I have been using a slightly patched version of this package with the RequestPayer flag hard-coded. I'm happy to parametrize this and make a pull request if this is something you'd be willing to merge.

https://github.com/pratheekrebala/s3p/commit/dcf53eb7a9e36f9f9661361f9f27caefd3b7982a

Another thing I found really useful was setting the "bucket-owner-full-control" flag which resolved ACL issues when moving files between organizations.

Thanks!

**Comment by shanebdavis** [comment]
v3.2 now supports several common copy options:

```
--acl
--cache-control
--content-disposition
--content-encoding
--content-language
--content-type
--expires
--request-payer
--storage-class
```

**Comment by pratheekrebala** [comment]
This looks great - thank you! 🎉
