### ISSUE TITLE
sync or copy with ACL

### ISSUE THREAD

**Issue by geopi1** [generalui/s3p#16]
Copying object does not include the ability to change the ACL (for example to bucket-owner-full-control)

similar to aws s3 sync s3://source s3://target --acl  bucket-owner-full-control

Cloud you add this support or help me add it myself?

**Comment by elliott-alt** [comment]
+1 this would be cool.  I am using a bucket policy that requires this, e.g.

```json
"Action": "s3:PutObject",
"Condition": {
    "StringEquals": {
        "s3:x-amz-acl": "bucket-owner-full-control"
    }
}
```

**Comment by shanebdavis** [comment]
v3.2 now supports several common copy options:

```
--acl
--cache-control
--content-disposition
--content-encoding
--content-language
--content-type
--expires
--request-payer
--storage-class
```
