### ISSUE TITLE
consume via API?

### ISSUE THREAD

**Issue by cprice404-aws** [generalui/s3p#28]
Is it possible to consume this project as a library (call it from other JS/TS code) as opposed to as a CLI tool?  If so are there any docs available?  Thanks!

**Comment by jeffski** [comment]
Looking for this too. Can you just use it with a Node Child process command, exec etc...?

**Comment by brown2021** [comment]
I tried every imaginable way on AWS Lambda and received errors of attempts to write to disk on a read-only file system. Aws lambda only lets you write to the /tmp directory. Is there a way to adjust this so it can work as an api?

**Comment by shanebdavis** [comment]
This is an excellent idea.

**Comment by shanebdavis** [comment]
Okay, I have a BETA for you to play with: https://github.com/generalui/s3p#api

There are a few tweaks I want to make, but it should do most of what you need. Please let me know what you think!

**Comment by brown2021** [comment]
Thanks for this. I did a mini-test.

 the command "npx s3p ls --bucket --quiet --api-example" did not work.
Also, the description you have of the output is not in line with the cli.

cli:
npx s3p ls --bucket [--prefix, etc... (optional] is supposed to output
contents of the bucket by default which can be filtered based on
prefix.(This is my favorite one. So I know it like I wrote it lol). see
attached screenshot.

API:
you have the output as listing the buckets. To get this output using the
cli, the command would be..
"npx s3p list-buckets"

If you look at the screenshot, it seems like there is something up with the
how the API is taking the credentials.

I hope this helps.

**Comment by brown2021** [comment]
Below is my unacceptable hack for executing cli commands for web api.
var cp = require('child_process');
cp.exec(`npx s3p ls --bucket ${t.bucket} --prefix ${t.prefix}`, function(
error, stdout, stderr) {
// handle err, stdout, stderr
console.log("data", t.bucket)
console.log("images", t.prefix)
if (error) {
console.error(`error: ${error.message}`);
res.json({"foo": error});
}
if (stderr) {
console.error(`stderr: ${stderr}`);
res.json({"foo": stderr});
}
console.log(`stdout:\n${stdout}`);
res.json({"foo": stdout});
});

**Comment by shanebdavis** [comment]
> the command "npx s3p ls --bucket --quiet --api-example" did not work.

This is a beta (v3), so it's not up on NPM yet. You need to npm install it into your project as per the instructions in the README.

**Comment by brown2021** [comment]
ah, I see.
The corresponding commands for the cli work for the API:
npx s3p list-buckets
npx s3p summarize --bucket
npx s3p ls --bucket --prefix(this works but differently. cli returns list
of strings of keys. API returns list of jsons of keys)

The corresponding commands for the cli DONT work for the API:
npx s3p cp --bucket --to-folder( --to-bucket) Error: Unhandled rejection

This is what I have tested so far.

Thanks

**Comment by shanebdavis** [comment]
Thanks for testing, @brown2021. Can you give me details? What command did you run? Can you give me a full copy of the error output?

I just tested both --to-bucket and --to-folder locally and they worked in my environment. I ran:

```javascript
require('s3p').cp({
   bucket: "xxx",
   prefix: "yyy",
   toBucket: "zzz"
})
```

**Comment by shanebdavis** [comment]
@brown2021 - question: What would you like to see from the `ls` method? 

I wanted to provide the most detailed data - which is the raw output from listObjects, but perhaps the default should be an array of item names? If so, I'd probably add a `--raw` option to enable the detailed, raw result.

**Comment by brown2021** [comment]
I think this is a great idea. the item names make it easy to grab whatever
item from the bucket in the workflow without having to parse.  the --raw
idea is perfect because we don't have to exclude data if we don't want to.

**Comment by brown2021** [comment]
The script is working now. It works locally.  When i execute it from
lambda, it executes successfully with no errors but no data is copied to
the bucket.  Maybe you are internally handling the errors that allow the
API execution to complete?

So the update is that it works in a local environment.  It may be something
on AWS not letting it through.

**Comment by shanebdavis** [comment]
You should get a list of individual items that failed to copy as part of the results. I was thinking some "on-" event handlers would be a nice future addition: "onError", "onCopy", "onFiltered" etc...

If you add "quiet: false" to your params, you should see details in the cloudwatch logs for your lamba.

**Comment by brown2021** [comment]
Thanks for the tip! I didnt see any errors from cloudwatch. But running the
following doesn't work. So if I want to store the images with a different
prefix,
it doesn't seem to appear.

    require('s3p').cp({
   bucket: "src",
   prefix: "images",
   toBucket: "target",
   toPrefix:"test",
   quiet: false
    });

**Comment by brown2021** [comment]
Hi Shane. Can you confirm that one cannot copy files from local directory
to s3 bucket as in the aws cli?

**Comment by shanebdavis** [comment]
You should definitely be able to copy from one prefix and replace it with another prefix in the target. Your command looks correct. I assume you tested it with the s3p cli locally and it worked?

I've never run S3P inside Lambda. I'm guessing there is some permissions issue happening, but I'm shooting in the dark what it could be.

**Comment by brown2021** [comment]
I ran it locally, it didnt work. This line of code fails for local to s3

 npx s3p cp --folder ./images --to-bucket img-lecole

**Comment by brown2021** [comment]
Sorry, i forgot to paste in the error below...

S3.list-error:

  bucket:     undefined

  prefix:     undefined

  startAfter: ""

  limit:      1000

  error:      Error:

    class: class Error

    stack:

      MissingRequiredParameter: Missing required key 'Bucket' in params

          at ParamValidator.fail
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:50:37)

          at ParamValidator.validateStructure
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:61:14)

          at ParamValidator.validateMember
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:88:21)

          at ParamValidator.validate
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:34:10)

          at Request.VALIDATE_PARAMETERS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:132:42)

          at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:106:20)

          at callNextListener
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:96:12)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:86:9

          at finish
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:386:7)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:404:9

          at SharedIniFileCredentials.get
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/credentials.js:127:7)

          at getAsyncCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:398:24)

          at Config.getCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:418:9)

          at Request.VALIDATE_CREDENTIALS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:81:26)

          at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:102:18)

          at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

          at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:688:14)

          at Request.transition
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:22:10)

          at AcceptorStateMachine.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/state_machine.js:14:12)

          at Request.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:408:15)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:797:12

          at Promise._execute
(/Users/engineer/Desktop/node_modules/bluebird/js/release/debuggability.js:384:9)


S3.list-error:

  bucket:     undefined

  prefix:     undefined

  startAfter: :O

  limit:      1000

  error:      Error:

    class: class Error

    stack:

      MissingRequiredParameter: Missing required key 'Bucket' in params

          at ParamValidator.fail
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:50:37)

          at ParamValidator.validateStructure
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:61:14)

          at ParamValidator.validateMember
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:88:21)

          at ParamValidator.validate
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:34:10)

          at Request.VALIDATE_PARAMETERS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:132:42)

          at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:106:20)

          at callNextListener
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:96:12)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:86:9

          at finish
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:386:7)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:404:9

          at SharedIniFileCredentials.get
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/credentials.js:127:7)

          at getAsyncCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:398:24)

          at Config.getCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:418:9)

          at Request.VALIDATE_CREDENTIALS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:81:26)

          at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:102:18)

          at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

          at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:688:14)

          at Request.transition
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:22:10)

          at AcceptorStateMachine.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/state_machine.js:14:12)

          at Request.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:408:15)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:797:12

          at Promise._execute
(/Users/engineer/Desktop/node_modules/bluebird/js/release/debuggability.js:384:9)


eachRecursive:

  startAfter: ""

  stopAt:


:~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  usePrefixBisect: false

  error:           Error:

    class: class Error

    stack:

      MissingRequiredParameter: Missing required key 'Bucket' in params

          at ParamValidator.fail
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:50:37)

          at ParamValidator.validateStructure
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:61:14)

          at ParamValidator.validateMember
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:88:21)

          at ParamValidator.validate
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:34:10)

          at Request.VALIDATE_PARAMETERS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:132:42)

          at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:106:20)

          at callNextListener
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:96:12)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:86:9

          at finish
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:386:7)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:404:9

          at SharedIniFileCredentials.get
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/credentials.js:127:7)

          at getAsyncCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:398:24)

          at Config.getCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:418:9)

          at Request.VALIDATE_CREDENTIALS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:81:26)

          at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:102:18)

          at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

          at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:688:14)

          at Request.transition
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:22:10)

          at AcceptorStateMachine.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/state_machine.js:14:12)

          at Request.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:408:15)

          at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:797:12

          at Promise._execute
(/Users/engineer/Desktop/node_modules/bluebird/js/release/debuggability.js:384:9)


Unhandled rejection MissingRequiredParameter: Missing required key 'Bucket'
in params

    at ParamValidator.fail
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:50:37)

    at ParamValidator.validateStructure
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:61:14)

    at ParamValidator.validateMember
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:88:21)

    at ParamValidator.validate
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/param_validator.js:34:10)

    at Request.VALIDATE_PARAMETERS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:132:42)

    at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:106:20)

    at callNextListener
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:96:12)

    at
/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:86:9

    at finish
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:386:7)

    at /Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:404:9

    at SharedIniFileCredentials.get
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/credentials.js:127:7)

    at getAsyncCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:398:24)

    at Config.getCredentials
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/config.js:418:9)

    at Request.VALIDATE_CREDENTIALS
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/event_listeners.js:81:26)

    at Request.callListeners
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:102:18)

    at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

    at Request.emit
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:688:14)

    at Request.transition
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:22:10)

    at AcceptorStateMachine.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/state_machine.js:14:12)

    at Request.runTo
(/Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:408:15)

    at /Users/engineer/Desktop/node_modules/aws-sdk/lib/request.js:797:12

    at Promise._execute
(/Users/engineer/Desktop/node_modules/bluebird/js/release/debuggability.js:384:9)

**Comment by shanebdavis** [comment]
It's perhaps not the nicest error, but did you include the `{bucket: "my-bucket"}` parameter?

**Comment by shanebdavis** [comment]
I released version 3 today with the new API functionality. I tweaked it slightly; I decided to make it match the CLI outputs as closely as possible. Quiet is false by default, and LS outputs keys only by default.

**Comment by brown2021** [comment]
sweet. I will test
