### ISSUE TITLE
Filter examples

### ISSUE THREAD

**Issue by nickperkins** [generalui/s3p#33]
I'd love to use a filter on a `ls` to get files created after x date. Some documentation on what data types is provided to the js function would be great. For example, I'm guessing `LastModified` is probably a string so needs to be converted to a date for comparing with greater/less than.

**Comment by shanebdavis** [comment]
The input objects to Filter are the same object returned by listObjectV2: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property

The Doc claims LastModified is a Date:

* Key — (String) The name that you assign to an object. You use the object key to retrieve the object.
* LastModified — (Date) Creation date of the object.
* ETag — (String) The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:
	* Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.
	* Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-C or SSE-KMS, have ETags that are not an MD5 digest of their object data.
	* If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption.
* Size — (Integer) Size in bytes of the object

* StorageClass — (String) The class of storage used to store the object.
Possible values include:
	* “STANDARD”
	* “REDUCED_REDUNDANCY”
	* “GLACIER”
	* “STANDARD_IA”
	* “ONEZONE_IA”
	* “INTELLIGENT_TIERING”
	* “DEEP_ARCHIVE”
	* “OUTPOSTS”
* Owner — (map) The owner of the object
	* DisplayName — (String) Container for the display name of the owner.
	* ID — (String) Container for the ID of the owner.
