### ISSUE TITLE
it can't be used in AWS China

### ISSUE THREAD

**Issue by jordan-huangwei** [generalui/s3p#41]
I configure the aws credential , and I can use `aws s3 ls` but I can't use s3p

**Comment by shanebdavis** [comment]
Can you provide a full copy of the output of running s3p?

**Comment by plthomasva** [comment]
> I configure the aws credential , and I can use `aws s3 ls` but I can't use s3p

Make sure you supply the region as an AWS SDK environment variable before running s3p, and you should be fine.

For example:

    export AWS_REGION=cn-north-1

Hope this helps!

**Comment by shanebdavis** [comment]
@jordan-huangwei Did this end up working for you?
