### ISSUE TITLE
Deprecated uuid@3.3.2

### ISSUE THREAD

**Issue by siebrand** [generalui/s3p#43]
Getting the following warning when installing s3p with node v16.2.0 (npm v7.15.2):

`npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.
  Older versions may use Math.random() in certain circumstances, which is known to be problematic. 
  See https://v8.dev/blog/math-random for details.`

**Comment by shanebdavis** [comment]
This requires an update to the AWS SDK v3 - which is quite different from v2. I'll be looking into it.

**Comment by siebrand** [comment]
Thanks for looking into this, Shane. I'm a bit confused. As far as I can tell, this issue wasn't resolved in the most recently published version 2.10.8 of s3p. However, you closed the issue. Did I miss something?

**Comment by siebrand** [comment]
@shanebdavis ping!

**Comment by siebrand** [comment]
Looks like #48 was opened for this.
