### ISSUE TITLE
S3p copy

### ISSUE THREAD

**Issue by DeepakRamegowdabdvt** [generalui/s3p#47]
I have a folder in the bucket  s3://AAA/XYZ/WWW/MYFOLDER ,
Destination bucket is "MYBackup" I want to just copy MYFOLDER to destination bucket "MYBackup" . The destination bucket should be  s3://MYBackup/MYFolder. How can i achieve this.Please help

Thanks

**Comment by shanebdavis** [comment]
I think what you want is:
```
s3p cp \
  --bucket from-bucket \
  --to-bucket to-bucket \ 
  --prefix AAA/XYZ/WWW/MYFOLDER \
  --to-prefix MYBackup/MyFolder
```
