### ISSUE TITLE
Can you confirm that one cannot copy files from local directory

### ISSUE THREAD

**Issue by shanebdavis** [generalui/s3p#50]
On Sun, Jul 18, 2021 at 3:19 AM jonathan brown ***@***.***> wrote:
> Hi Shane. Can you confirm that one cannot copy files from local directory
> to s3 bucket as in the aws cli?

**Comment by shanebdavis** [comment]
@brown2021

S3P can't copy FROM the local file system yet because listing the local file system works considerably different from listing an S3 bucket. 

A quick fix would be to load up a list of all the local files into memory and then simulating the S3 listBucket API internally for the local file system. The problem with this is it could use a great deal of memory if you have a ton of files you want to copy.

My question to you is how many files do you want to copy from the local file system?

**Comment by brown2021** [comment]
I am attempting to read a tar file from local.

**Comment by shanebdavis** [comment]
It sounds like it would be useful to have from-local support even if it is memory capped and can't do more than, say, a few hundred thousand files before running into memory constraints.

> Note, S3P doesn't copy individual files any faster than `aws s3 cp`

**Comment by brown2021** [comment]
Ah, got it
