### ISSUE TITLE
Failures exit with zero exit code

### ISSUE THREAD

**Issue by bgardner-noggin** [generalui/s3p#51]
If I run s3p with bad arguments, or with bad values it exits with zero exit codes eg

npx s3p sync --foo

npx s3p sync --bucket "doesnot" --to-bucket "exist"

**Comment by bgardner-noggin** [comment]
```
diff --git a/bin/s3p b/bin/s3p
index b1270d2..c924425 100755
--- a/bin/s3p
+++ b/bin/s3p
@@ -1,2 +1,12 @@
 #!/usr/bin/env node
-require('../build').S3PCli.main();
+
+async function invoke() {
+	try {
+		await require('../build').S3PCli.main();
+	} catch (err) {
+		console.log(err);
+		process.exit(1);
+	}
+}
+
+invoke();
```

I tried submitting a pull request, but got a permissions error

**Comment by shanebdavis** [comment]
Good find! I'll work on a fix. 

I think simplicity is essential to maintainable code. A simpler fix would have been to just append a `.catch` to the end of the bin/s3p file:

```javascript
#!/usr/bin/env node
require('../build').S3PCli.main()
.catch(error) {
  console.log(error);
  process.exit(1);
};
```

The right fix is to actually patch `@art-suite/cli`. That'll fix this problem for all apps using the CLI tool. I'll do that promptly :).

**Comment by shanebdavis** [comment]
Done! s3p v3.3.0 published.

**Comment by bgardner-noggin** [comment]
Thanks, and thanks for the improved code.
