### ISSUE TITLE
How does the --filter option work?

### ISSUE THREAD

**Issue by pathcode** [generalui/s3p#52]
Documentation is unclear on it. 

If I wanted to use it like the --exclude option on the other s3 tools, how would I do that?

**Comment by shanebdavis** [comment]
Filter uses an arbitrary JavaScript function to filter your final results. Always use `--prefix`, `--start-after` and/or `--end-at` first to narrow the items listed from S3. Then, you can use `--filter` to further filter the list using arbitrary code.

For example you could filter on storage class with:

```shell
> s3p cp --filter "js:({StorageClass}) => StorageClass == 'STANDARD'" ...
```

Details on the values you can filter on can be found in the AWS SDK's listObjectsV2 method: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property

* Key — (String)The name that you assign to an object. You use the object key to retrieve the object.
* LastModified — (Date)Creation date of the object.
* ETag — (String)The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:
	* Objects created by the PUT Object, POST Object, or Copy operation, or through the Amazon Web Services Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.
	* Objects created by the PUT Object, POST Object, or Copy operation, or through the Amazon Web Services Management Console, and are encrypted by SSE-C or SSE-KMS, have ETags that are not an MD5 digest of their object data.
	* If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption.
* Size — (Integer)Size in bytes of the object
* StorageClass — (String)The class of storage used to store the object.
Possible values include:
	* “STANDARD”
	* “REDUCED_REDUNDANCY”
	* “GLACIER”
	* “STANDARD_IA”
	* “ONEZONE_IA”
	* “INTELLIGENT_TIERING”
	* “DEEP_ARCHIVE”
	* “OUTPOSTS”
* Owner — (map)The owner of the object
	* DisplayName — (String)Container for the display name of the owner.
	* ID — (String)Container for the ID of the owner.

**Comment by shanebdavis** [comment]
There are more examples in the help: `npx s3p cp --help`
