### ISSUE TITLE
s3p cp to instance copies the data twice

### ISSUE THREAD

**Issue by gilShin** [generalui/s3p#54]
When I use --to-folder with --prefix and --to-prefix, I see the files on my instance in both <dest folder>/<to prefix value> and under <dest folder>/<prefix value>

Meaning, the following command:
s3p cp --bucket abc --to-folder /def --prefix prefixA --to-prefix prefixB

will result in the following folder hirerchy:
/def/
    prefixB/<files>
    prefixA/<files>

**Comment by shanebdavis** [comment]
There was a bug that --to-prefix was ignored when using --to-folder. This is now fixed in v3.3.4.
