### ISSUE TITLE
How do I filter based on object owner?

### ISSUE THREAD

**Issue by svaranasi-traderev** [generalui/s3p#55]
In an attempt to sync files between buckets cross-account, I routinely encounter files in the source S3 bucket that were uploaded by a different owner. S3P does a hard fail on this whereas AWS S3 cli simply ignores them.

So, I was trying to [add a filter](https://github.com/generalui/s3p/blob/ff8e6bb62e640b6b2db36590b2ec9c0fa5e10d44/source/S3Parallel/S3PCli.caf#L24) based on file-owner so I only copy files that the syncing user has access to, but I've no idea how. I tried something based on a [previous issue-answer](https://github.com/generalui/s3p/issues/52) but it didn't work:

```
npx s3p@3.3.2 sync --bucket source-bucket --to-bucket dest-bucket --acl bucket-owner-full-control --overwrite --filter"js:({Owner}) => Owner.DisplayName == 'my-account-alias'"
```

How do I go about doing this?

**Comment by shanebdavis** [comment]
This has been fixed, but you'll need to add the `--fetch-owner` command-line option. This is not turned on by default because it adds ~10% overhead to listings.
