### ISSUE TITLE
Issues with --to-prefix in sync command

### ISSUE THREAD

**Issue by jdyer09** [generalui/s3p#6]
Probably user error, but I can't get this to work at all. Names changed slightly, but the command at issue is:

```
npx s3p sync --dryrun --to-bucket my-special-bucket --bucket my-special-bucket --prefix path/goes_here/ --to-prefix path/goes_here_archive/ --start-after path/goes_here/dump_date=2020-03-01 --verbose
```
But what winds up on the output is:
```
options:
  dryrun:     true
  toBucket:   :my-special-bucket
  bucket:     :my-special-bucket
  prefix:     :path/goes_here/
  toPrefix:   :path/goes_here_archive/
  startAfter: :path/goes_here/dump_date=2020-03-01
  verbose:    true

aws s3 cp 's3://my-special-bucket/path/goes_here/dump_date=2020-03-05/year=2020/month=4/part-00002-tid-longint-uuid.snappy.parquet' 's3://my-special-bucket/path/goes_here/dump_date=2020-03-05/year=2020/month=4/part-00002-tid-longint-uuid.snappy.parquet'
```
Notably, it won't change the prefix to what's in the toPrefix.  Do I understand the syntax incorrectly, or is there another issue at hand?  Changing the destination bucket seems to work just fine.

**Comment by pjbull** [comment]
@jdyer09 I think I may have fixed this in this PR if you want to test: https://github.com/generalui/s3p/pull/7

**Comment by jdyer09** [comment]
It looks like @shanebdavis made changes that covered this issue, so I'll close it
