### ISSUE TITLE
How do I filter object on the basis of name , given that the name should be present in the array 

### ISSUE THREAD

**Issue by moneychaudharywork** [generalui/s3p#62]

**Comment by shanebdavis** [comment]
There are several ways to filter based on the name:

- `--prefix xxx` will only match keys with that prefix
- `--start-after xxx` and/or `--stop-at xxx` will only match keys `>=` and `<` the specified keys respectfully
- `--filter "js:(item) => ..."` will only copy items where the custom js function returns true.

For examples, run: `npx s3p cp --help`
