### ISSUE TITLE
Can I use this solution in a mobile application to speed uploads to s3?

### ISSUE THREAD

**Issue by eyekay234** [generalui/s3p#69]
I have a mobile application where users upload videos and images that are processed on ec2 instance on aws and then stored on selected s3 buckets. 

I want to know if this can be used for making user uploads to s3 buckets faster as presently there is a huge latency being experienced on the app when users try to upload videos they create using the mobile application

**Comment by shanebdavis** [comment]
This isn't really the right tool for that. This tool is designed for transferring dozens if not hundreds of files _at the same time_. It won't make transferring single files any faster.
