### ISSUE TITLE
any ideas on how to show  when last a S3 bucket was used with API call ? 

### ISSUE THREAD

**Issue by mcousins20** [generalui/s3p#75]
Would like to output 

{
  "bucket-a-name": Date the bucket was last used. 
  "bucket-b-name": Date the bucket was last used. 
}

**Comment by shanebdavis** [comment]
It depends. If the data you need is in the response data from https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax, then yes, S3P could help with this. For example, LastModified is returned for each item. S3P could scan all items in parallel and look for the maximum value of that field and return it (and return which item it was from).

I don't think there is a way to tell the last time an S3 bucket was read from, though.

**Comment by shanebdavis** [comment]
The s3p CLI's `map` option would make it possible to do this operation without writing much custom code. You'd just pass in a small mapper and reducer on the command-line to select the LastModified field and return the max respectively.

From the examples:

```
> npx s3p map --help
[...]
s3p map --bucket my-bucket --reduce "js:(a, b) => a.LastModified > b.lastModified ? a : b" --finally "js:({Key}) => Key"
# return the key of the newest item
```

Which you could alter simply to be:
```
s3p map --bucket my-bucket --reduce "js:(a, b) => a.LastModified > b.lastModified ? a : b" --finally "js:({lastModified}) => lastModified"
```

**Comment by shanebdavis** [comment]
That will only work for one bucket, so, finally, if you run that last command with the --api-example option, it'll show you how to make that same call in javascript.

```bash
npx s3p map --bucket my-bucket --reduce "js:(a, b) => a.LastModified > b.lastModified ? a : b" --finally "js:({lastModified}) => lastModified" --api-example
```

```javascript
require('s3p').map({
   bucket: "my-bucket",
   reduce: (a, b) => a.LastModified > b.lastModified ? a : b,
   finally: ({lastModified}) => lastModified
})
// > Promise
```

From there you can write some code to iterate over all your buckets and the summarize the results.

**Comment by mcousins20** [comment]
Thank you. I will give that a try.

**Comment by shanebdavis** [comment]
Let me know how it goes!

**Comment by mcousins20** [comment]
Hey Shane, 
So I'm able to run it against one bucket.
`npx s3p map --bucket atanillumina --reduce "js:(a, b) => a.LastModified > b.lastModified ? a : b"`
how it looks : 
`LastModified:      2022-07-19 17:56:38 UTC
ChecksumAlgorithm: []
Size:              78176738
StorageClass:      STANDARD`

So to follow the steps for the API, I would do this :
`npx s3p map --bucket foo --reduce "js:(a, b) => a.LastModified > b.lastModified ? a : b" --api-example`
`node`
paste
`require('s3p').listBuckets({
      bucket: "foo",
      reduce: (a, b) => a.LastModified > b.lastModified ? a : b
   })`

I know this produces the creation date :  

`require('s3p').listBuckets({
   bucket: "foo",
   quiet: true
}).then((out) => console.log(out));`

**Comment by mcousins20** [comment]
Any ideas on using the API to get the last modified date, don't the s3 bucket? Not very familiar with Javascript

**Comment by mcousins20** [comment]
@shanebdavis
