### ISSUE TITLE
GovCloud support?

### ISSUE THREAD

**Issue by checkerbomb** [generalui/s3p#84]
Does s3p support GovCloud? I can list all my buckets on a commercial AWS account without issue. Using access keys and buckets in a GovCloud account results in `InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
`. Is this expected? Am I doing something wrong?

**Comment by shanebdavis** [comment]
I haven't tested it with GovCloud. I did a version bump on the AWSv2 library I'm using, but AWS wants everyone to migrate to v3 - which I haven't done yet. That's probably why GovCloud isn't working.

**Comment by shanebdavis** [comment]
Dependent on: #48

**Comment by shanebdavis** [comment]
I just bumped s3p to the AWS SDK v3. It's possible it will now work with GovCloud. If you can access your GovCloud account with the amazon CLI tools, I'd think it should also work with the AWS SDK v3...

Could you test and see?

**Comment by checkerbomb** [comment]
Just tested and can confirm, I was able to successfully list a bucket in GovCloud with v3.5.2! Thanks for the update!
