### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by teto** [generalui/s3p#85]
hi,

I am trying to package s3p for my distribution and not having git tags matching releases makes it harder. I chose the commit whose message contained a "version" number but I am not sure it's the same commit used on npmjs.com

**Comment by shanebdavis** [comment]
Are you somehow trying to pull directly from this repo for your packaging rather than use the NPMjs.com package?

I could make git-tags, but I'd like to understand your use-case better. Usually people would just use NPM to do it. If this is the only NPM you need, you could do:

```
# inside your distribution
echo {} > package.json
npm install s3p@3.5
npx s3p ...
```

Even more performant would be to do that locally, and then copy the package.json and package-lock.json files into your distribution and then use:
```
npm ci # faster than npm install
npx s3p ...
```

**Comment by teto** [comment]
> Are you somehow trying to pull directly from this repo for your packaging rather than use the NPMjs.com package?

Yes, I use nix, a source-based packager. I am not that familiar with npm is it possible to get a source archive from https://www.npmjs.com/ ? I prefer to build referencing this github repo anyway because it lets me build from an arbitrary revision

> npm install s3p@3.5

this wont work since nix builds in a sandbox without internet access, or more accurately it can download from the internet only if it can check the integrity of the files, via a checksum. Also once nix builds a package, it lives in a simple folder in a cache and installing a package consists in just copying a folder from a cache which i guess is even faster than `npm ci`.

Anyway I dont want to drown you into irrelevant nix technical details, it works fine with a commit revision the main point is irrelevant to nix: as a developer, if I want to look at the code of a specific s3p version, I am not sure which commit matches the release, git tags make "which revision to look at" clearer.

**Comment by shanebdavis** [comment]
Your ask for tagged releases is perfectly reasonable of course. I'll try to get that into my workflow.

I'm curious, though, why you can't run `npm install s3p@3.5.2`. If you are cloning from the github repo, you still need to `npm install` and then `npm run build` before anything will work... How does that work if you have no network connection?

**Comment by shanebdavis** [comment]
I made a test tag and release called 3.5.2. Does that work for you?

**Comment by teto** [comment]
> I'm curious, though, why you can't run npm install s3p@3.5.2. If you are cloning from the github repo, you still need to npm install and then npm run build before anything will work... How does that work if you have no network connection?

You can access internet only if you can validate the file content with a checksum, like the package-lock.json contains. Ty for the tags.
